# Generated by Django 4.2.5 on 2023-09-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('buyer', 'Buyer')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
