# Generated by Django 4.2.5 on 2023-09-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usertype',
        ),
    ]
